

\begin{center}
\begin{large}

```{r, results = 'asis', eval = TRUE}
make_authors()
```

\end{large}
\end{center}

\vspace{5mm}

\begin{center}
\textbf{Abstract}  
\end{center}

\vspace{5mm}
\begin{center}
\begin{changemargin}{3cm}{3cm} 

This paper provides new empirical evidence regarding the effect and return on investment of privately managed malaria control activities (indoor residual spraying with pesticides) on worker absenteeism in Mozambique. We analyze 4 years of malaria control and worker health and absenteeism data from a large sugar processing facility in Mozambique. We find that the benefits outweight the costs (ie, there is a positive return on investment) even when the consideration of benefits is limited to those directly accrued by the company. These findings suggest that the private sector may have an important role to play in malaria control in endemic areas.

\end{changemargin}
\end{center}

\vspace{20mm}

\noindent\fbox{%
    \parbox{\textwidth}{%
        \subsection*{Research Highlights}
        \begin{itemize}
          \item Large, individual-level worker absenteeism data from malaria endemic zone
          \item Quantifies effect of indoor residual spraying on absenteeism
          \item Estimates cost-effectiveness of malaria control from investment standpoint
          \item Results suggest that private sector could play a significant role in malaria elimination
        \end{itemize}
        \vspace{2mm}
    }%
}

\vfill
\null

\subsection*{Keywords}
\textbf{Malaria; Investment; Health; Productivity; Agriculture; Absenteeism}

\vspace{3mm}

\newpage