# Introduction  

Malaria accounts for a half million annual deaths worldwide [@White2014] [@World2016] [@Ashley2018]. Though rapid improvements in technology and funding have lead to important reductions in marlaria's global burden, the scale-up in activities required for eradication ("the worldwide interruption of transmission") [@TheLancet2011] will mean new partnerships and actors. One promising - albeit atypical - potential stakeholder in global malaria eradication is the private sector, given its omnipresence and potential to benefit directly from the elimination of malaria. But little evidence exists demonstrating how private sector entities can engage with malaria control and benefit at the firm level.


At the societal level, malaria has a large economic impact. By affecting saving, investment [@Shretta2016], risk perception, productivity, absenteeism [@Nonvignon_2016], human capital accumulation [@CastelBranco2014], mortality, and costs of care [@Sachs2002], malaria likely has a negative effect on GDP and growth [@McCarthy_2000] [@Orem_2012]. Because of the relative affordability of most intereventions and the enormous societal costs of malaria, most forms of malaria control are cost-effective when a public welfare perspective is assumed, such as when a government provides the financing [@White_2011] [@Purdy_2013] [@Howard_2017].

From the persepctive of the private sector, however, investing in malaria control is not so clear-cut. Public health interventions targetting malaria - and their corresponding cost-effectiveness evaluations - most often focus on impacts pertaining to public welfare, such as an increase in life years adjusted for disability or quality  [@Goodman1999] [@Shretta2016] [@Lee2017] [@Hanson2004]. Though population-level health is certainly of importance to businesses, and improvements in health incidentally improve the economy at all levels [@World1999] [@Bloom2008] [@Vecchi_2013], these improvements may be too disperse or long-term to incentivize private sector involvement in health campaigns. 

100% of the Mozambican population are at risk of malaria, living in what the WHO classifies as a "high transmission" area [@Moonasar_2016]. Annually, Mozambique has more than 8 million clinical malaria cases (an annual incidence of approximately 300 per 1,000 residents), with an estimated 14,000 deaths. Malaria accounts for 29% of all deaths, and 42% of deaths among those under five years of age [@estatistica2009]. Since 2013, Mozambique has seen a gradual increase in the incidence of malaria [@Moonasar_2016]. 100% of the malaria in Mozambique is of the Plasmodium falciparum species, with Anopheles funestus, gambiae, and arabiensis as the primary mosquito vectors of the disease [@whoprof]. 

A significant sector of the economy in Mozambique is dominated by large-scale foreign direct investment projects [@Robbins2012], and the role of the private sector in health generally, and malaria specifically, is unequivocally important. Large agriculture and extractive industry firms take up wide swaths of land and employ hundreds of thousands  [@German2013]. The Mozambican state has encouraged large-scale entreprise with the aim of general economic development [@Buur2012]. And where large firms exist, they often take on social roles such as housing and health care [@Winkler]. At times, this role is necessary from a purely practical standpoint; in other cases, it is employed under the auspices of "corporate social responsibility" [@Azemar2009]. Regardless of the language used, it is clear that private industry plays an important role in public health in Mozambique [@Robbins2012] [@CastelBranco2014]. 

Several cases exist of foreign firms engaging in large-scale malaria control campaigns [@Mouzin2011] [@Han] [@Bennett_2017] [@Kaula_2017]. But these studies generally consider population health as the outcome measure of interest, rather than worker absenteeism or productivity. Similarly, they often neglect to differentiate between those clinical costs which are absorbed by the local health system versus those which are absorbed by the firm itself. In the literature, making the "investment case" for malaria control or elimination generally implies that the investor is the public sector, and takes into account those costs and benefits which are applicable from a public welfare point of view [@Shretta_2017]; though appropriate in most cases (the government or institutions interested in public welfare primarily being the primary malaria control agents in most locations), the findings of these studies are rarely applicable to the private sector, and even less so at granular levels (such as an individual firm). In the case of a private firm not interested in "corporate social responsibility", it is not clear whether investing in malaria control would be profitable or not. This lack of clarity not only discourages investment, but also makes it difficult for governments to pinpoint the correct of amount of subsidy (if applicable) to encourage private sector scale-up in malaria control.

To address the question of the profitability of malaria control activities from the standpoint of a private firm, we analyze data during a 4 year period from a private sugar facility in Southern Mozambique. We assess the effect of indoor residual spraying (IRS) on the absenteeism and health of workers, and demonstrate that the firm's engagement in malaria control not only improved worker health, but also generated a positive return on investment from a pure accounting perspective.

The structure of the paper is as follows. After a brief review of the existing literature on the subject of private sector investment in malaria control and its effects on worker productivity, we provide an overview of the sugar company under study, and the epidemiology of malaria in the nearby area, as well as in Mozambique as a whole. We then give an overview of the data collected, and outline the theoretical and methdological assumptions and tools that underly our analysis. In the results, we show the effectiveness of the company's malaria control program in reducing absences, and translate this reduction into cost savings. Our discussion covers potential implications from this study in terms of policy and investment, as well as the paper's limitations. 

## Background Literature

\todo{Will add 3-5 paragraphs of background lit review}

Our study adds to the existing literature in several ways. \improvement{Will add details here.}

## Study area

Sugar has been systematically cultivated in Mozambique since the late 1800s. The Incomati Estates company, a small sugarcane processing facility started by a Scotsman on the banks of the Incomati River in 1913, was the first firm to export sugar from Mozambique. Following its purchase by international investors in the 1950s, it (along with the rest of the industry) expanded significantly, exporting to both Europe and the United States. In the late 1960s, a Portuguese family opened the Maragra Açúcar company, while a group of foreign investors started the nearby Marracuene Agrícola Açucareira mill. By the early 1970s, sugar grew to account for greater than 10% of Mozambique's national exports. Nationalized following independence in 1977, the industry's production levels fell from 320,000 annual tons to fewer than 15,000 by 1992. After the end of the civil war, foreign investment revived the sugar industry, and by 2011 production had surpassed its 1972 peak. 


The mill of the Maragra Açucar SA (a subsidary of the Illovo sugar company, henceforth referred to as "Maragra") was nationalized in the 1970s (like all other Mozambican mills), went through a period of low production, and then fell completely out of use by 1984. It re-opened in private hands in 1992, and was renovated by a group of international investors in 1998. Today, Maragra accounts for roughly one quarter of Mozambique's overall sugar production (second only to the nearby Xinavane mill run by the Hulett Sugar Tongaat company) [@sutton]. With a favorably close location to the port of Maputo, ample land, approximately 5,000 employees (of which three quarters are seasonal), and a mill with the capacity to process not only all the sugarcane grown on Maragra's land, but also the cane of the many nearby smallholders [@OLaughlin2016], Maragra has so far been able to weather the 2016 Mozambican crisis and concurrent collapse in global sugar prices. 

Maragra is located in the district of Manhiça, a semi-rural area in Southern Mozambique

```{r, fig.width = 6, fig.align='center', fig.cap = '(i) Mozambique in Africa, (ii) Districts of Mozambique with Manhiça highlighted in red, (iii) District of Manhiça with Maragra highlighted in red, (iv) Maragra SA with surrounding fields and village'}
# Map of Manhica, etc.
# Libraries
library(tidyverse)
library(raster)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(broom)
library(ggthemes)

# Get each countries shapefile
countries <- c('Mozambique')
iso3s <- c('MOZ')
for(i in 1:length(countries)){
  message('Fetching data for ', countries[i])
  x <- getData(name = 'GADM', level = 2, country = iso3s[i])
  assign(tolower(countries[i]),
         x,
         envir = .GlobalEnv)
}

# Define which districts are "special" -------------
specials <- 'Manhiça'

# Mozambique
mozambique@data$special <- FALSE
mozambique@data$special[mozambique@data$NAME_2 %in% specials] <- TRUE

# Combine all data into a "long" / "tidy" format
make_long <- function(x, region = "NAME_2"){
  shp_df <- broom::tidy(x, region = region)
  return(shp_df)
}
mozambique_long <- make_long(mozambique) %>% mutate(country = 'Mozambique')
combined <- mozambique_long
combined$special <- combined$id %in% specials
# combined$special[!combined$special] <- NA
# Get a map of africa to use as a background
# from the cism package!
africa <- cism::africa
africa_long <- make_long(africa, region = 'COUNTRY')
africa_long$special <- africa_long$id %in% countries

g1 <-
  ggplot() +
  geom_polygon(data = africa_long,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = grey(0.6),
               alpha = 1,
               color = 'white',
               lwd = 0.3) +
  geom_polygon(data = combined,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = grey(0.3)) +
  geom_polygon(data = combined %>% filter(!is.na(special) & special),
               aes(x = long,
                   y = lat,
                   group = group,
                   fill = special)) +
  scale_fill_manual(name = '',
                    values = c('darkorange'),
                    na.value = NA) +
  coord_cartesian() +
  ggthemes::theme_map() +
  theme(legend.position = 'none') +
  # redraw country lines
  geom_polygon(data = africa_long,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = NA,
               alpha = 1,
               color = 'white',
               lwd = 0.3) + coord_map() +
  labs(title = 'i.')
country_map <- function(the_country = 'Gabon'){
  ggplot(data = combined %>% filter(country == the_country),
         aes(x = long,
             y = lat,
             group = group,
             fill = special)) +
    geom_polygon(#alpha = 0.8,
                 lwd = 0.3,
                 color = grey(0.6)) +
    theme_map() +
    coord_map() + 
    scale_fill_manual(name = '', values = c('darkgrey', 'darkred')) +
    theme(legend.position = 'none')
}
g2 <- country_map('Mozambique') +
  labs(title = 'ii.')

mar <- data.frame(lat = -25.4498802, long = 32.777661)
man3_fortified <- cism::man3_fortified
g3 <- ggplot(data = man3_fortified,
             aes(x = long,
                 y = lat)) +
  geom_polygon(aes(group = group),
               # alpha = 0.8,
                 lwd = 0.3,
                 color = grey(0.6)) +
  geom_point(data = mar,
             aes(x = long,
                 y = lat),
             color = 'red') +
  geom_point(data = mar,
             aes(x = long,
                 y = lat),
             color = 'red',
             size = 4, 
             pch = 1) +
  geom_point(data = mar,
             aes(x = long,
                 y = lat),
             color = 'red',
             size = 6, 
             pch = 1) +
  geom_point(data = mar,
             aes(x = long,
                 y = lat),
             color = 'red',
             size = 9, 
             pch = 1) +
    theme_map() +
    coord_map() + 
    theme(legend.position = 'none') +
  labs(title = 'iii')

library(ggmap)
# if('.hdf.RData' %in% dir()){
#   load('.hdf.RData')
# } else {
  hdf <- ggmap::get_map(location = c(lon = mar$long, lat = mar$lat), maptype = 'satellite', zoom = 14)
#   save(hdf, file = '.hdf.RData')
# }

g4 <- ggmap::ggmap(hdf) +
  theme_map() +
  labs(title = 'iv')

Rmisc::multiplot(g1, g2, g3, g4, cols = 2)
```



Details on Manhica

Details on Mozambique


