---
title: Is malaria control profitable? Return on investment of privately-managed residential
  fumigations at a large sugarcane processing facility in Southern Mozambique
csl: apa_modified.csl
date: ''
output:
  html_document:
    df_print: paged
  pdf_document:
    includes:
      in_header: preamble.sty
    keep_tex: yes
    latex_engine: xelatex
  word_document: default
fig_width: 8
fig_height: 6
bibliography: bibliography.bib
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = FALSE}

# Packages
library(tidyverse)
library(knitr)
library(Hmisc)
library(brew)
library(maragra)
library(knitr)
library(RColorBrewer)
library(extrafont)
library(kableExtra)
loadfonts()
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               # dev = "cairo_pdf",
               fig.pos="!h",
               fig.path = 'figures/')
opts_knit$set(width=75)
options(xtable.comment = FALSE)

```

```{r}
source('paper_prepare.R')
```

```{r}
# Build document from contents of directory
# Get a list of all the child documents
rmds <- list.files(pattern = '*.Rmd', recursive = FALSE, include.dirs = FALSE)
# Must include an underscore!
rmds <- rmds[grepl('_', rmds)]


chunks <- paste0("\n\n```{r child = '", 
                 rmds, 
                 "'}\n```\n")

# Write our order / child-calls to a doc
file_connection <- file('children.Rmd')
writeLines(paste0('---\noutput: html_document\n---\n\n', 
                  chunks), 
           file_connection)
close(file_connection)

```

```{r child='children.Rmd', echo = FALSE}
```

```{r, results='hide'}
file.remove('children.Rmd')
```


